### ISSUE TITLE
The dataset produced by CBench

### ISSUE THREAD

**Issue by EloiseXu** [amirjamez/COBAYN#2]
Hi, I've been trying to use more compiler passes to produce a dataset for training. However, when I run cbench by myself, each application won't last for more than 30 seconds on a dataset when default loop wrap parameter is used. Besides, the difference between the wall time or the cpu time is not as obvious as in cBench_onPandaboard_24app_5ds.csv when different configuration combinations are applied. Since we run cbench in a similar hardware environment, I guess this is because we run cbench in a different way. So, would you tell what the loop wrap was and how you obtained the dataset? Did you use __compile and __run in cbench to compile and run those 24 applications?
  Thanks a lot!

**Comment by amirjamez** [comment]
Hi @EloiseXu, That's true. Cbench are a collection of small c sequential kernels and te default dataset are very and thus, executing them won't take long. 
What you can do is:

 

1. Use/define a larger input dataset in each kernel's folder in **_ccc_info_datasets**. Normally, it points to a  <*_data> folder. For instance for automotive_qsort, there is **automotive_qsort_data** and you can pass the larger sizes or even use your own preferred data. 

2. Use the loop wrap method defined as **loop_wrap** in all <__run> files. This will execute the specific kernel multiple times. Say, 20 - 100 times. 

3. You can easily automate the execution flow by modifying the global script under the root directory <all_compile>, etc. 

Good luck.
